language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install: "pip install tox nose"

# command to run tests
script: 
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then tox -e py26; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then tox -e py27; fi
  - sudo mkdir /mnt/gluster-object/test
  - sudo mkdir /mnt/gluster-object/test2
  - sudo mkdir /mnt/gluster-object/gsmetadata
  - tox -e functest
